version: '3.8'

services:
  redpanda:
    image: vectorized/redpanda:latest
    ports:
      - "9092:9092"
      - "9644:9644"
    command: redpanda start --smp 1 --memory 16G --reserve-memory 0M --overprovisioned --node-id 0 --check=false
